[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["ws"] }
mongodb = "3.1.0"
serde = "1.0.210"
tokio = { version = "1.40.0", features = ["full"] }
