[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
crossbeam = "0.8.4"
serde = "1.0.210"
serde_json = "1.0"
tungstenite = { version = "0.24.0", features = ["native-tls"] }

[profile.dev.package."*"]
opt-level = 2
